### ISSUE TITLE
autoscaler ignores ongoing deployments when trying to change number of agents

### ISSUE THREAD

**Issue by JackQuincy** [wbuchwalter/Kubernetes-acs-engine-autoscaler#1]
ACS uses aync operations to track its deployments, https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-async-operations . Currently ACS doesn't behave well if multiple deployments are ongoing at the same time. This autoscaler just calls repeatedly and doesn't check if the previous runs deployment is still ongoing.

**Comment by wbuchwalter** [comment]
I added a basic check here: https://github.com/wbuchwalter/Kubernetes-acs-autoscaler/commit/e414493d75180de5b3215aaee89f541635286bf6
It can be optimized later on, at least it shouldn't be causing issues anymore.
