### ISSUE TITLE
CUDA libraries on nodes

### ISSUE THREAD

**Issue by dopplesoldner** [wbuchwalter/Kubernetes-acs-engine-autoscaler#11]
Hi 
I am not sure if I missed a step but how do we get CUDA libraries on the nodes? I was able to create a cluster following your steps but got stuck at running gpu based programs (errors are around missing cuda libraries)

Thanks

**Comment by wbuchwalter** [comment]
Closing this issue since it's not related to the autoscaler.
Follow up here: https://github.com/wbuchwalter/blog-posts/issues/1
