### ISSUE TITLE
No such option: --acs-deployment

### ISSUE THREAD

**Issue by jskulavik** [wbuchwalter/Kubernetes-acs-engine-autoscaler#35]
Hi @wbuchwalter: is the [example scaling deployment](https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/blob/master/scaling-deployment.yaml) pointing to the correct image?  I receive `Error: no such option: --acs-deployment` when trying to specify a deployment in the yaml.

**Comment by wbuchwalter** [comment]
Fixed by #36.
Thanks for your contribution 👍
