### ISSUE TITLE
Deployment 'X' could not be found.

### ISSUE THREAD

**Issue by jskulavik** [wbuchwalter/Kubernetes-acs-engine-autoscaler#37]
I've tried to deploy the [scaling-deployment](https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/blob/master/scaling-deployment.yaml) with several --acs-deployment flags set, and consistently receive the message: `Deployment '[acs-deployment]' could not be found`.  

Where can I clearly find and specify the acs-deployment to pass to the --acs-deployment flag?  azuredeploy.json or azuredeploy.parameters.json?  I'll gladly submit a PR to the docs once this is clear.  Thank you @wbuchwalter!

**Comment by wbuchwalter** [comment]
When you deployed your cluster you did something like:
`az group deployment create --name myDeployment ...`

If you don't remember which name you used, you can go in the Azure portal, in your resource group, under the deployment tab. This would be the name of the very first deployment.

If you didn't use the `-n` or `--name` flag when deploying the cluster then you don't need the `--acs-deployment` flag.

Assuming your deployment name is `myDeployment`, in `scaling-deployment.yaml` , you should have:
```yaml
[...]
   command:
            - python
            - main.py
            - --resource-group 
            - <your-group-name>
            - --acs-deployment
            - myDeployment
            - -vvv
[...]
```

**Comment by jskulavik** [comment]
Thanks @wbuchwalter, that's what I thought and tried, but I've missed something along the way.  Closing for now until I get it sorted.

**Comment by MirzaSikander** [comment]
If using helm to deploy, specify the `acsdeployment` parameter in `values.yaml` 

```
acsenginecluster:
  acsdeployment: <deployment name>
```
