### ISSUE TITLE
Imperative manual scaling

### ISSUE THREAD

**Issue by wbuchwalter** [wbuchwalter/Kubernetes-acs-engine-autoscaler#40]
By @noajshu :
> One functionality that would be super helpful would be CLI verbs for imperative cluster scaling --
e.g.
```bash
python main.py --scale-pool --pool-name 'mypool0' --pool-size 12
```
> to just get mypool0 to 12 nodes, disregarding current pod statuses. I think those functions are present in this module in some form -- any tips for surfacing those?

**Comment by wbuchwalter** [comment]
That's interesting indeed.
In the current state of things, you would still need to do something like this:
```
python main.py --resource-group wibuchgpu  \
 --service-principal-app-id 'xxx' --service-principal-secret 'xxx' \
 --service-principal-tenant-id 'xxx' \
 --kubeconfig-private-key 'xxx==' \
 --client-private-key 'xxx' \
 --kubeconfig /root/.kube/config \
 --scale-pool --pool-name 'mypool0' --pool-size 12
```
which is a bit cumbersome for a simple command. The best way to do it would be to add a hook in the autoscaler so that it can receive commands at run time (a little bit like helm/tiller). I need to check the complexity of such a solution.

Also if you have a running instance of the autoscaler in your cluster, the node you manually scale up would still be killed after the period specified by `--idle-threshold`. Would that be fine for your use case?

**Comment by yuvipanda** [comment]
Perhaps another way is to just make the manual scale up / down a different command entrypoint? So we can run it manually without having to run the entire scaler? https://github.com/Azure/acs-engine/issues/979 scaling acs-engine clusters manually up and down over time is very error prone, with seemingly disasterous consequences if done wrong :)

**Comment by wbuchwalter** [comment]
@yuvipanda Yes :) We are discussing just this here: https://github.com/Azure/acs-engine/issues/1060

**Comment by yuvipanda** [comment]
Awesome :) I'm following that issue :)

**Comment by wbuchwalter** [comment]
Closing in favor of Azure/acs-engine#1060
