### ISSUE TITLE
Spare agents configuration ignores second agent pool

### ISSUE THREAD

**Issue by oryagel** [wbuchwalter/Kubernetes-acs-engine-autoscaler#42]
Hi.
We have two agent pools, let's call them pool1 and pool2.
I configured `--spare-agents 2` which should make sure that there are at least four agents, two for each pool.
The behaviour that I see is that the autoscaler keeps two agents for pool1 but removes all agents for pool2.

Thanks

**Comment by wbuchwalter** [comment]
Hey :hand: 
Can you provide more info on your setup, so I can try to reproduce your issue?
* Autoscaler logs where the unwanted downscale happened
* The parameter you are using to start the autoscaler
* Ideally also the json file you used as input to `acs-engine` to generate your cluster.

**Comment by oryagel** [comment]
Thanks.
I currently unable to reproduce that behaviour. I didn't change anything in my configuration, so I assume it will happen again.
I'm closing the issue for now.
