### ISSUE TITLE
Adding an agent pool to a cluster that was up-scaled by the ‘autoscaler’

### ISSUE THREAD

**Issue by segeva** [wbuchwalter/Kubernetes-acs-engine-autoscaler#56]
Is adding an agent pool to a cluster that was ‘upscaled’ by the ‘autoscaler’ possible?
We used  the method described on https://github.com/Azure/acs-engine/issues/621 to add an agent pool.
We also tested the autoscaler to “manually” upscale a specific pool (after the upscale completed we switched to –dry-run mode) on another cluster.
It will be useful for us to combine the ‘autoscaler’ with the ability to add agent pool when required. 
I assume that there is a need to manually adjust the agent count/offset to match the last deployment by the ‘autoscaler’ but is that sufficient?

**Comment by wbuchwalter** [comment]
I have never really tried this scenario.
If you add a new pool to the cluster, you might be able to make the autoscaler work properly by restarting it and passing the name of the new deployment (where you added the pool) to the autoscaler with the `--acs-deployment` flag. 

> I assume that there is a need to manually adjust the agent count/offset to match the last deployment by the ‘autoscaler’ but is that sufficient.

You can check [this documentation ](https://github.com/Azure/acs-engine/tree/master/examples/scale-up) that lists the step you need to take to properly scale up.

**Comment by segeva** [comment]
This appears to be a tricky one especially if we want to add an agent pool after a deployment by the ‘autoscaler’. Our templates on files are no longer in sync with the actual deployment.
We will re-evaluate when there is support for labels/nodeSelector  which is related to our use case.
