### ISSUE TITLE
Scaling down to 0 VMs on agent pools

### ISSUE THREAD

**Issue by adinin** [wbuchwalter/Kubernetes-acs-engine-autoscaler#61]
Is there currently no way to scale down to having 0 VMs on an agent pool? 

Reading through the code, it looks like template_processing.py has unroll_vm, unroll_* functions that rely on existing resources to get a template (for creating new resources during scale up). With 0 VMs, there would be nowhere to get the template from. 

Alternatively, we could load templates from external file. That would allow for maximum drain of resources (especially if you have a few agent pools with expensive VMs). 

Is this already possible in some way that I'm not aware of? If not, is anyone interested in having this feature?

Thank you!

**Comment by wbuchwalter** [comment]
@adinin This has been implemented a while back. The AS should be able to scale any pool to 0 agents, and scale it back up later on.
However, you will still have a few agent nodes in your cluster to support the different system pods (kube-dns replication for example) and the autoscaler pod itself, unless you manually move evreything on a master.
Let me know if you tried and this doesn't work.

**Comment by wbuchwalter** [comment]
Assuming this is solved. let me know if not.
