### ISSUE TITLE
ACS-Engine v.0.12.5 Helm problems

### ISSUE THREAD

**Issue by lauxtermann-aram** [wbuchwalter/Kubernetes-acs-engine-autoscaler#78]
I provisioned a cluster with acs-engine v.0.12.5 and:

1. Calico
2. Data Encryption at rest

when I helm install with the following (uncommented keys) in a values.yaml:

> image:
>   repository: wbuchwalter/kubernetes-acs-engine-autoscaler
>   tag: 2.1.1
>   pullPolicy: IfNotPresent
> rbac:
>   install: true
>   apiVersion: v1beta1
> acsenginecluster:
>   resourcegroup: 
>   azurespappid: 
>   azurespsecret: 
>   azuresptenantid: 
>   subscriptionid: 
>   kubeconfigprivatekey: 
>   clientprivatekey: 
>   caprivatekey: 
>   etcdclientprivateKey: 
>   etcdServerprivateKey: 
>   acsdeployment: 

I get this error:

**2018-02-10 11:20:19,720 - autoscaler.cluster - WARNING - Unexpected error: &lt;class 'requests.exceptions.HTTPError'&gt;**
 
I think that the helm installer (chart is: latest 2.11) does not integrate:
  etcdclientprivateKey: 
  etcdServerprivateKey: 

Because I see the same manifest as version :

```
{
                "name": "AZURE_SP_APP_ID",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "k8s-acs-engine-autoscaler",
                    "key": "azure-sp-app-id"
                  }
                }
              },
              {
                "name": "AZURE_SP_SECRET",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "k8s-acs-engine-autoscaler",
                    "key": "azure-sp-secret"
                  }
                }
              },
              {
                "name": "AZURE_SP_TENANT_ID",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "k8s-acs-engine-autoscaler",
                    "key": "azure-sp-tenant-id"
                  }
                }
              },
              {
                "name": "KUBECONFIG_PRIVATE_KEY",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "k8s-acs-engine-autoscaler",
                    "key": "kubeconfig-private-key"
                  }
                }
              },
              {
                "name": "CLIENT_PRIVATE_KEY",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "k8s-acs-engine-autoscaler",
                    "key": "client-private-key"
                  }
                }
              },
              {
                "name": "CA_PRIVATE_KEY",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "k8s-acs-engine-autoscaler",
                    "key": "ca-private-key"
                  }
                }
              }
```

Can anyone assist? 
Tnx

**Comment by wbuchwalter** [comment]
Can you try with `latest` tag instead of `2.1.1`?

**Comment by lauxtermann-aram** [comment]
Hi William, thank you for the quick response! I am passing the latest tag to the values.yaml

> image:
>   repository: wbuchwalter/kubernetes-acs-engine-autoscaler
>   tag: latest
>   pullPolicy: IfNotPresent
> rbac:

 and now i am still seeing that no envar is set for EtcServerPrivateKey. 

Any ideas?

**Comment by lauxtermann-aram** [comment]
I am getting this error:

**autoscaler - ERROR - Missing Azure credentials. Please provide service_principal_app_id, service_principal_secret, service_principal_tenant_id and subscription_id.** 

But in my values.yaml I have exactly the same child selectors as in the templates

> image:
>   repository: wbuchwalter/kubernetes-acs-engine-autoscaler
>   tag: latest
>   pullPolicy: IfNotPresent
> rbac:
>   install: true
>   apiVersion: v1beta1
> acsenginecluster:
>   resourcegroup: xxx
>   azurespappid: xxx
>   azurespsecret: xxx
>   azuresptenantid: xxx
>   subscriptionid: xxx
>   kubeconfigprivatekey: xxx 
>   clientprivatekey: xxx
>   caprivatekey: xxx
>   etcdclientprivateKey: xxx
>   etcdServerprivateKey: xxx
>   acsdeployment: xxx


Do you see any problems in the values.yaml?

**Comment by lauxtermann-aram** [comment]
Hi @wbuchwalter 

1. I have used the last version of the code base.
2. Made my own templates, based upon your helm templates (hard-coded)
3. Went into my container and checked if all the ENV_VARS are correct
4. Removed the index from sys.exc_info()[1] >> sys.exc_info(), so I would get a bigger trace.

```
        if debug:
            # In debug mode, we don't want to catch error. Let the app crash
            # explicitly
            return self.loop_logic()
        else:
            try:
                return self.loop_logic()
            except CloudError as e:
                logger.error(e)
            except:
                logger.warn("Unexpected error: {}".format(sys.exc_info()))
                return False
```

The last error I am getting is:

**WARNING - Unexpected error: (<class 'ValueError'>, ValueError("invalid literal for int() with base 10: 'kube'",), <traceback object at 0x7fba5b12ca08>)**

Do you have a idea where the have declared in my config. Do you have any idea which int() is needed?

**Comment by wbuchwalter** [comment]
@lauxtermann-aram There was a type in `values.yaml`.
`etcdServerprivateKey` should instead be `etcdserverprivateKey` (no capital s).

**Comment by lauxtermann-aram** [comment]
@wbuchwalter Thank you. Everything is working. I used the yaml templates and added hardcode strings to them. I know you are busy, but if you have the time it would be nice to release a new helm chart 2.12. If I can assist please let me know?
