### ISSUE TITLE
Azure kubectl get hpa - target unknown

### ISSUE THREAD

**Issue by SnehaJosephSTS** [wbuchwalter/Kubernetes-acs-engine-autoscaler#95]
I am following this link to autoscale my AKS deployment ([https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-scale])

On running "kubectl get hpa" via the Azure Cloud Shell; I am always getting an "unknown" target.

![image](https://user-images.githubusercontent.com/41419331/44846563-53604c00-ac6e-11e8-8fc1-2f5fca1939ed.png)

Even on increasing the load; I observed that the pod CPU usage simply get limited by the limits i have set in the .yaml file . No new pods get generated by the hpa.

Why isn't the hpa creating new pods?

**Comment by wbuchwalter** [comment]
Hi, You have got the wrong repository.
Open your issue here instead: https://github.com/kubernetes/kubernetes

This might help you as well: https://github.com/Azure/AKS/issues/318
